### ISSUE TITLE
Events are not triggering

### ISSUE THREAD

**Issue by anbushgm** [swiftyspiffy/StreamElementsNET#2]
Events related with Tips/Hosts (didn't test others) aren't triggering at all. Although OnConnected / OnAuthenticated / OnAuthenticationFailure / OnSent / OnReceivedRawMessage are working good

**Comment by swiftyspiffy** [comment]
I believe I fixed it with this commit here: https://github.com/swiftyspiffy/StreamElementsNET/commit/2463327a939b16ff98e2bbdc2d21cdf34cc12a43 . Try pulling that change down and see if your events are working again. I left a comment in that commit, but basically the payload changed slightly, resulting in events not being detected.

**Comment by anbushgm** [comment]
Are not triggering by StreamElements test(emulate) 
![image](https://user-images.githubusercontent.com/35369361/209323464-09f09860-f71d-442c-8d29-6b1fea6a56fa.png)

**Comment by anbushgm** [comment]
OnReceivedRawMessage is catching that tho
![image](https://user-images.githubusercontent.com/35369361/209324106-e1f91ee8-ee84-4c23-9177-89cc5a42854e.png)

**Comment by anbushgm** [comment]
Hovewer it works perfect with real events, thanks!
